### ISSUE TITLE
Native compiler return value: ‘[BC30560] 'GeneratedCodeAttribute' is ambiguous in the namespace 'System.CodeDom.Compiler'.

### ISSUE THREAD

**Issue by AmirImam** [amh1979/Reporting#22]
Hi
RDLC report on .Net 5 API project throws this error when I use parameters in **Execute** function
`Native compiler return value: ‘[BC30560] 'GeneratedCodeAttribute' is ambiguous in the namespace 'System.CodeDom.Compiler'.`
It works fine if I didn't send any parameters

- .Net 5
- AspNetCore.Reporting 2.1.0
- System.CodeDom 5.0.0

**Edit 1**:
It works fine with parameters on local but throws this error after publishing on IIS as (self-contained/ win-x86) or (Framework-dependent/Portable)

**Edit 2:**
I realized that the error appears when I drag a parameter into the report itself, even if I sent parameters with Execute function. So I can send any parameters and add parameters to the report but not dragging them into it.

**Edit 3**
Parameters and anything that contains a date or time are causing a crash

Thank you

**Comment by italoaguiar** [comment]
Same problem here. It works locally but when deployed in azure it gives an error.
**[BC30560] 'GeneratedCodeAttribute' is ambiguous in the 'System.CodeDom.Compiler' namespace.**

I found this alternative repository and it worked perfectly for me
https://github.com/lkosson/reportviewercore

**Comment by brownjr38** [comment]
We had the same issue.  We started with an RDLC file that was copied to the output during the build.  This file is in a .NET Standard 2.0 project.  The project consuming it and generating the PDF is .NET 5.0.

We switched to the https://github.com/lkosson/reportviewercore NuGet package and changed the RDLC file to an embedded resource.  Then we had no problems.

In our local DEV environment both approaches worked, but only the 2nd approach worked with the self-contained published application.

With the 1st approach, our 1st error was the following:
`...
AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;The definition of the report 'E:\Octopus\Applications\Development\MyApp\1.0.207_6\Reports\MyFile.rdlc' is invalid.
An unexpected error occurred in Report Processing.
Access to the path 'C:\Windows\TEMP\Compiler_dfe72de6ed8341d795957ecac5aa7259' is denied.
 ---> AspNetCore.Reporting.DefinitionInvalidException: The definition of the report 'E:\Octopus\Applications\Development\MyApp\1.0.207_6\Reports\MyFile.rdlc' is invalid.
An unexpected error occurred in Report Processing.
Access to the path 'C:\Windows\TEMP\Compiler_dfe72de6ed8341d795957ecac5aa7259' is denied. ---> AspNetCore.ReportingServices.ReportProcessing.ReportProcessingException: An unexpected error occurred in Report Processing.
Access to the path 'C:\Windows\TEMP\Compiler_dfe72de6ed8341d795957ecac5aa7259' is denied. ---> System.UnauthorizedAccessException: Access to the path 'C:\Windows\TEMP\Compiler_dfe72de6ed8341d795957ecac5aa7259' is denied.
   --- End of inner exception stack trace ---
   at AspNetCore.Reporting.InternalLocalReport.EnsureExecutionSession()
   at AspNetCore.Reporting.InternalLocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
   at AspNetCore.Reporting.InternalLocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at AspNetCore.Reporting.InternalLocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at AspNetCore.Reporting.LocalReport.Execute(RenderType renderType, Int32 pageIndex, Dictionary`2 parameters, String findString)
...`

After we added permissions to the TEMP directory we had the following error:
`...
AspNetCore.Reporting.LocalProcessingException: An error occurred during local report processing.;The definition of the report 'E:\Octopus\Applications\Development\MyApp\1.0.207_6\Reports\MyFile.rdlc' is invalid.
An unexpected error occurred while compiling expressions. Native compiler return value: ‘[BC30560] 'GeneratedCodeAttribute' is ambiguous in the namespace 'System.CodeDom.Compiler'.’.
 ---> AspNetCore.Reporting.DefinitionInvalidException: The definition of the report 'E:\Octopus\Applications\Development\MyApp\1.0.207_6\Reports\MyFile.rdlc' is invalid.
An unexpected error occurred while compiling expressions. Native compiler return value: ‘[BC30560] 'GeneratedCodeAttribute' is ambiguous in the namespace 'System.CodeDom.Compiler'.’. ---> AspNetCore.ReportingServices.ReportProcessing.ReportProcessingException: An unexpected error occurred while compiling expressions. Native compiler return value: ‘[BC30560] 'GeneratedCodeAttribute' is ambiguous in the namespace 'System.CodeDom.Compiler'.’.
   --- End of inner exception stack trace ---
   at AspNetCore.Reporting.InternalLocalReport.EnsureExecutionSession()
   at AspNetCore.Reporting.InternalLocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, CreateAndRegisterStream createStreamCallback, Warning[]& warnings)
   at AspNetCore.Reporting.InternalLocalReport.InternalRender(String format, Boolean allowInternalRenderers, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at AspNetCore.Reporting.InternalLocalReport.Render(String format, String deviceInfo, PageCountMode pageCountMode, String& mimeType, String& encoding, String& fileNameExtension, String[]& streams, Warning[]& warnings)
   at AspNetCore.Reporting.LocalReport.Execute(RenderType renderType, Int32 pageIndex, Dictionary`2 parameters, String findString)
...`

After ruling out permissions, we tried the new library and it worked.

**Comment by bhawnakoul** [comment]
I also kept running into the same issue after giving permissions to report file as well as to temp folder. It kept complaining about not being able to validate expressions even with a blank report file. I did not come across any issues in my local environment. But as soon as I deployed it to Dev Environment, all issues started coming up. I ended up using a different library "ReportViewerCore.NETCore" which worked like charm for me.

**Comment by Snehal14283** [comment]
I had same issue. After R&D I found that if we used concatenation within expression in RDLC. It generates this error. Try to remove all the fields (expression) from the RDLC and put just static label text and generate the report. 

Hope this should work for you as well.
